"""Init

Revision ID: 29d8a0bf12e9
Revises: a044a8d1130c
Create Date: 2023-06-16 14:19:16.265289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d8a0bf12e9'
down_revision = 'a044a8d1130c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
