"""Init

Revision ID: 2da39177abf1
Revises: 29d8a0bf12e9
Create Date: 2023-06-16 14:25:12.456073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da39177abf1'
down_revision = '29d8a0bf12e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
