"""Init

Revision ID: 804fc31f1575
Revises: 2da39177abf1
Create Date: 2023-06-16 14:26:34.308033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804fc31f1575'
down_revision = '2da39177abf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
