"""Init

Revision ID: 8637becc63dd
Revises: fa398170e91e
Create Date: 2023-06-16 14:34:40.532080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8637becc63dd'
down_revision = 'fa398170e91e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
