"""Init

Revision ID: a044a8d1130c
Revises: 00b1b6bf7ee1
Create Date: 2023-06-16 14:17:42.081925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a044a8d1130c'
down_revision = '00b1b6bf7ee1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
