"""Init

Revision ID: fa398170e91e
Revises: d3a5fe88940d
Create Date: 2023-06-16 14:30:43.719011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa398170e91e'
down_revision = 'd3a5fe88940d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
